/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/source/2014_-_porsche_918_spyder_rigged__mid-poly.glb 
Author: UniBlend (https://sketchfab.com/UniBlend)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/2014-porsche-918-spyder-rigged-mid-poly-1d34d42ce58c48f49146346ff67e492d
Title: 2014 - Porsche 918 Spyder (Rigged) | Mid-Poly
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/2014_-_porsche_918_spyder_rigged__mid-poly.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.743, 0.374]} rotation={[-1.571, 0, 0]}>
        <group position={[0, -0.005, -0.742]} rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0.476, -0.027]}>
            <mesh geometry={nodes.Object_584.geometry} material={materials['Plastic_-_Matte_Black']} />
            <mesh geometry={nodes.Object_586.geometry} material={materials.Structure} position={[0.743, -0.115, -1.405]} />
            <mesh geometry={nodes.Object_588.geometry} material={materials.Structure} position={[-0.739, -0.112, -1.406]} />
            <mesh geometry={nodes.Object_590.geometry} material={materials.Structure} position={[0.458, -0.299, -1.489]} />
            <mesh geometry={nodes.Object_592.geometry} material={materials.Structure} position={[-0.458, -0.299, -1.489]} />
          </group>
          <mesh geometry={nodes.Object_6.geometry} material={materials['Body_Paint_-_GT_Silver_Metalic']} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.Belt} position={[0.342, 0.538, -0.016]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.Belt} position={[0.335, 0.34, -0.117]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.Belt} position={[-0.265, 0.396, -0.139]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.Detail} position={[0, 0.745, 0.375]} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.Detail} position={[0, 0.725, -2.208]} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.Detail} position={[0, 0.704, -2.26]} />
          <mesh geometry={nodes.Object_20.geometry} material={materials['Carbon_Fiber_-_Interior']} position={[0.03, 0.69, 0.281]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_22.geometry} material={materials['Metal_-_Chrome']} position={[0.247, 0.569, 0.33]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.Interior_Detail} position={[0.155, 0.622, 0.497]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_26.geometry} material={materials['Metal_-_Black']} position={[0.029, 0.633, 0.08]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_28.geometry} material={materials['Interior_Detail_-_Palstic']} position={[0.078, 0.627, 0.431]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.Rubber} position={[0, 0.756, 0.262]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_32.geometry} material={materials.Fabric} position={[0, 0.362, 0.143]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_34.geometry} material={materials['Metal_-_Chrome']} position={[0, 0.945, -0.855]} />
          <mesh geometry={nodes.Object_36.geometry} material={materials['Plastic_-_Glossy_Black']} position={[0.035, 0.704, 0.758]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_38.geometry} material={materials['Plastic_-_Glossy_Black']} position={[-0.515, 0.904, -0.438]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_40.geometry} material={materials['Plastic_-_Glossy_Black']} position={[0.515, 0.904, -0.438]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_42.geometry} material={materials['Metal_-_Chrome']} position={[0.649, 0.698, 0.119]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_44.geometry} material={materials.Structure} position={[0.761, 0.343, 1.253]} />
          <mesh geometry={nodes.Object_46.geometry} material={materials.Structure} position={[-0.761, 0.343, 1.253]} />
          <mesh geometry={nodes.Object_48.geometry} material={materials.Leather} position={[0.082, 0.613, 0.565]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_50.geometry} material={materials['Plastic_-_Glossy_Black']} position={[0.214, 0.697, 0.611]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_52.geometry} material={materials['Plastic_-_Glossy_Black']} position={[0.115, 0.682, 0.733]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_54.geometry} material={materials['Metal_-_Chrome']} position={[-0.051, 0.787, 0.785]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_56.geometry} material={materials['Metal_-_Chrome']} position={[0.005, 0.786, 0.779]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_58.geometry} material={materials.Touch_Screen_Glass} position={[0.145, 0.664, 0.555]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_60.geometry} material={materials['Plastic_-_Glossy_Green']} position={[0.358, 0.758, 0.649]} rotation={[0.249, 0, -0.458]} />
          <mesh geometry={nodes.Object_62.geometry} material={materials['Plastic_-_Glossy_Black']} position={[0.337, 0.768, 0.652]} rotation={[0.249, 0, -0.458]} />
          <mesh geometry={nodes.Object_64.geometry} material={materials['Emissive-Green']} position={[0.222, 0.738, 0.612]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_66.geometry} material={materials['Emissive-Green']} position={[0.22, 0.738, 0.612]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_68.geometry} material={materials['Emissive-Green']} position={[0.218, 0.738, 0.612]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_70.geometry} material={materials['Emissive-Green']} position={[0.217, 0.738, 0.612]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_72.geometry} material={materials['Emissive-Green']} position={[0.215, 0.738, 0.612]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_74.geometry} material={materials['Emissive-Green']} position={[0.213, 0.738, 0.611]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_76.geometry} material={materials['Emissive-Green']} position={[0.212, 0.738, 0.611]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_78.geometry} material={materials['Emissive-Green']} position={[0.21, 0.738, 0.611]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_80.geometry} material={materials['Emissive-Green']} position={[0.221, 0.753, 0.617]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_82.geometry} material={materials['Emissive-Green']} position={[0.22, 0.753, 0.617]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_84.geometry} material={materials['Emissive-Green']} position={[0.218, 0.753, 0.616]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_86.geometry} material={materials['Emissive-Green']} position={[0.216, 0.753, 0.616]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_88.geometry} material={materials['Emissive-Green']} position={[0.214, 0.753, 0.616]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_90.geometry} material={materials['Emissive-Green']} position={[0.213, 0.753, 0.616]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_92.geometry} material={materials['Emissive-Green']} position={[0.211, 0.753, 0.616]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_94.geometry} material={materials['Emissive-Green']} position={[0.209, 0.753, 0.615]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_96.geometry} material={materials['Emissive-Green']} position={[0.472, 0.73, 0.608]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_98.geometry} material={materials['Emissive-Green']} position={[0.474, 0.732, 0.608]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_100.geometry} material={materials['Emissive-Green']} position={[0.475, 0.735, 0.609]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_102.geometry} material={materials['Emissive-Green']} position={[0.476, 0.737, 0.609]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_104.geometry} material={materials['Emissive-Green']} position={[0.476, 0.74, 0.61]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_106.geometry} material={materials['Emissive-Green']} position={[0.476, 0.742, 0.611]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_108.geometry} material={materials['Emissive-Green']} position={[0.476, 0.745, 0.611]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_110.geometry} material={materials['Emissive-Green']} position={[0.476, 0.747, 0.612]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_112.geometry} material={materials['Emissive-Green']} position={[0.475, 0.749, 0.613]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_114.geometry} material={materials['Emissive-Green']} position={[0.472, 0.754, 0.614]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_116.geometry} material={materials['Emissive-Green']} position={[0.471, 0.755, 0.615]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_118.geometry} material={materials['Emissive-Green']} position={[0.469, 0.757, 0.616]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_120.geometry} material={materials['Emissive-Green']} position={[0.467, 0.758, 0.616]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_122.geometry} material={materials['Emissive-Green']} position={[0.465, 0.76, 0.617]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_124.geometry} material={materials['Emissive-Green']} position={[0.462, 0.76, 0.617]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_126.geometry} material={materials['Emissive-Green']} position={[0.459, 0.761, 0.618]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_128.geometry} material={materials['Emissive-Green']} position={[0.457, 0.761, 0.618]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_130.geometry} material={materials['Emissive-Green']} position={[0.454, 0.761, 0.618]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_132.geometry} material={materials['Emissive-Green']} position={[0.452, 0.76, 0.619]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_134.geometry} material={materials['Emissive-Green']} position={[0.449, 0.759, 0.619]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_136.geometry} material={materials['Emissive-Green']} position={[0.447, 0.758, 0.619]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_138.geometry} material={materials['Emissive-Green']} position={[0.444, 0.757, 0.618]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_140.geometry} material={materials['Emissive-Green']} position={[0.442, 0.755, 0.618]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_142.geometry} material={materials['Emissive-Green']} position={[0.441, 0.753, 0.618]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_144.geometry} material={materials['Emissive-Green']} position={[0.439, 0.751, 0.617]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_146.geometry} material={materials['Emissive-Green']} position={[0.438, 0.749, 0.617]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_148.geometry} material={materials['Emissive-Green']} position={[0.437, 0.747, 0.616]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_150.geometry} material={materials['Emissive-Green']} position={[0.437, 0.744, 0.616]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_152.geometry} material={materials['Emissive-Green']} position={[0.436, 0.742, 0.615]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_154.geometry} material={materials['Emissive-Green']} position={[0.437, 0.738, 0.614]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_156.geometry} material={materials['Emissive-Green']} position={[0.437, 0.736, 0.613]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_158.geometry} material={materials['Emissive-Green']} position={[0.438, 0.734, 0.613]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_160.geometry} material={materials['Emissive-Green']} position={[0.439, 0.732, 0.612]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_162.geometry} material={materials['Emissive-Green']} position={[0.44, 0.729, 0.611]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_164.geometry} material={materials['Emissive-Green']} position={[0.474, 0.751, 0.613]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_166.geometry} material={materials['Emissive-Green']} position={[0.222, 0.73, 0.61]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_168.geometry} material={materials['Emissive-Green']} position={[0.22, 0.73, 0.61]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_170.geometry} material={materials['Emissive-Green']} position={[0.219, 0.73, 0.61]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_172.geometry} material={materials['Emissive-Green']} position={[0.217, 0.73, 0.61]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_174.geometry} material={materials['Emissive-Green']} position={[0.215, 0.73, 0.61]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_176.geometry} material={materials['Emissive-Green']} position={[0.214, 0.73, 0.609]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_178.geometry} material={materials['Emissive-Green']} position={[0.212, 0.73, 0.609]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_180.geometry} material={materials['Emissive-Green']} position={[0.21, 0.73, 0.609]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_182.geometry} material={materials['Emissive-Green']} position={[0.222, 0.746, 0.615]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_184.geometry} material={materials['Emissive-Green']} position={[0.22, 0.746, 0.615]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_186.geometry} material={materials['Emissive-Green']} position={[0.218, 0.746, 0.614]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_188.geometry} material={materials['Emissive-Green']} position={[0.216, 0.746, 0.614]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_190.geometry} material={materials['Emissive-Green']} position={[0.215, 0.746, 0.614]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_192.geometry} material={materials['Emissive-Green']} position={[0.213, 0.746, 0.614]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_194.geometry} material={materials['Emissive-Green']} position={[0.211, 0.746, 0.614]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_196.geometry} material={materials['Emissive-Green']} position={[0.208, 0.706, 0.598]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_198.geometry} material={materials.LCD_Emissive} position={[0.246, 0.772, 0.621]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_200.geometry} material={materials.LCD_Emissive} position={[0.243, 0.774, 0.622]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_202.geometry} material={materials.LCD_Emissive} position={[0.24, 0.777, 0.622]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_204.geometry} material={materials.LCD_Emissive} position={[0.237, 0.779, 0.622]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_206.geometry} material={materials.LCD_Emissive} position={[0.233, 0.781, 0.623]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_208.geometry} material={materials.LCD_Emissive} position={[0.23, 0.783, 0.623]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_210.geometry} material={materials.LCD_Emissive} position={[0.226, 0.784, 0.623]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_212.geometry} material={materials.LCD_Emissive} position={[0.222, 0.785, 0.622]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_214.geometry} material={materials.LCD_Emissive} position={[0.214, 0.786, 0.622]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_216.geometry} material={materials.LCD_Emissive} position={[0.211, 0.786, 0.622]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_218.geometry} material={materials.LCD_Emissive} position={[0.207, 0.786, 0.621]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_220.geometry} material={materials.LCD_Emissive} position={[0.203, 0.785, 0.62]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_222.geometry} material={materials.LCD_Emissive} position={[0.199, 0.784, 0.62]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_224.geometry} material={materials.LCD_Emissive} position={[0.195, 0.783, 0.619]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_226.geometry} material={materials.LCD_Emissive} position={[0.192, 0.781, 0.618]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_228.geometry} material={materials.LCD_Emissive} position={[0.189, 0.779, 0.617]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_230.geometry} material={materials.LCD_Emissive} position={[0.185, 0.777, 0.616]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_232.geometry} material={materials.LCD_Emissive} position={[0.183, 0.774, 0.615]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_234.geometry} material={materials.LCD_Emissive} position={[0.18, 0.772, 0.614]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_236.geometry} material={materials.LCD_Emissive} position={[0.337, 0.715, 0.634]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_238.geometry} material={materials.LCD_Emissive} position={[0.342, 0.715, 0.634]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_240.geometry} material={materials.LCD_Emissive} position={[0.346, 0.716, 0.635]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_242.geometry} material={materials.LCD_Emissive} position={[0.35, 0.717, 0.635]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_244.geometry} material={materials.LCD_Emissive} position={[0.355, 0.718, 0.636]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_246.geometry} material={materials.LCD_Emissive} position={[0.359, 0.72, 0.636]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_248.geometry} material={materials.LCD_Emissive} position={[0.363, 0.722, 0.637]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_250.geometry} material={materials.LCD_Emissive} position={[0.367, 0.724, 0.638]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_252.geometry} material={materials.LCD_Emissive} position={[0.37, 0.727, 0.638]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_254.geometry} material={materials.LCD_Emissive} position={[0.374, 0.729, 0.639]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_256.geometry} material={materials.LCD_Emissive} position={[0.377, 0.733, 0.64]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_258.geometry} material={materials.LCD_Emissive} position={[0.379, 0.736, 0.641]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_260.geometry} material={materials.LCD_Emissive} position={[0.382, 0.739, 0.642]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_262.geometry} material={materials.LCD_Emissive} position={[0.384, 0.743, 0.643]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_264.geometry} material={materials.LCD_Emissive} position={[0.296, 0.73, 0.639]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_266.geometry} material={materials.LCD_Emissive} position={[0.3, 0.727, 0.638]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_268.geometry} material={materials.LCD_Emissive} position={[0.291, 0.736, 0.641]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_270.geometry} material={materials.LCD_Emissive} position={[0.293, 0.733, 0.64]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_272.geometry} material={materials.LCD_Emissive} position={[0.307, 0.722, 0.637]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_274.geometry} material={materials.LCD_Emissive} position={[0.288, 0.739, 0.642]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_276.geometry} material={materials.LCD_Emissive} position={[0.303, 0.724, 0.638]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_278.geometry} material={materials.LCD_Emissive} position={[0.324, 0.716, 0.635]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_280.geometry} material={materials.LCD_Emissive} position={[0.328, 0.715, 0.634]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_282.geometry} material={materials.LCD_Emissive} position={[0.311, 0.72, 0.636]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_284.geometry} material={materials.LCD_Emissive} position={[0.32, 0.717, 0.635]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_286.geometry} material={materials.LCD_Emissive} position={[0.286, 0.743, 0.643]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_288.geometry} material={materials.LCD_Emissive} position={[0.315, 0.718, 0.636]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_290.geometry} material={materials.LCD_Emissive} position={[0.333, 0.715, 0.634]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_292.geometry} material={materials.LCD_Emissive} position={[0.218, 0.786, 0.622]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_294.geometry} material={materials.LCD_Emissive} position={[0.386, 0.747, 0.644]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_296.geometry} material={materials.LCD_Emissive} position={[0.388, 0.751, 0.645]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_298.geometry} material={materials.LCD_Emissive} position={[0.389, 0.755, 0.646]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_300.geometry} material={materials.LCD_Emissive} position={[0.39, 0.759, 0.648]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_302.geometry} material={materials.LCD_Emissive} position={[0.39, 0.764, 0.649]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_304.geometry} material={materials.LCD_Emissive} position={[0.391, 0.768, 0.65]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_306.geometry} material={materials.LCD_Emissive} position={[0.39, 0.772, 0.651]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_308.geometry} material={materials.LCD_Emissive} position={[0.39, 0.777, 0.653]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_310.geometry} material={materials.LCD_Emissive} position={[0.389, 0.781, 0.654]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_312.geometry} material={materials.LCD_Emissive} position={[0.386, 0.789, 0.656]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_314.geometry} material={materials.LCD_Emissive} position={[0.384, 0.793, 0.657]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_316.geometry} material={materials.LCD_Emissive} position={[0.382, 0.797, 0.658]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_318.geometry} material={materials.LCD_Emissive} position={[0.379, 0.8, 0.659]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_320.geometry} material={materials.LCD_Emissive} position={[0.377, 0.804, 0.66]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_322.geometry} material={materials.LCD_Emissive} position={[0.374, 0.807, 0.661]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_324.geometry} material={materials.LCD_Emissive} position={[0.37, 0.809, 0.662]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_326.geometry} material={materials.LCD_Emissive} position={[0.367, 0.812, 0.663]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_328.geometry} material={materials.LCD_Emissive} position={[0.363, 0.814, 0.663]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_330.geometry} material={materials.LCD_Emissive} position={[0.359, 0.816, 0.664]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_332.geometry} material={materials.LCD_Emissive} position={[0.355, 0.818, 0.664]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_334.geometry} material={materials.LCD_Emissive} position={[0.35, 0.819, 0.665]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_336.geometry} material={materials.LCD_Emissive} position={[0.346, 0.82, 0.665]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_338.geometry} material={materials.LCD_Emissive} position={[0.342, 0.821, 0.665]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_340.geometry} material={materials.LCD_Emissive} position={[0.337, 0.821, 0.665]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_342.geometry} material={materials.LCD_Emissive} position={[0.333, 0.821, 0.665]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_344.geometry} material={materials.LCD_Emissive} position={[0.328, 0.821, 0.665]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_346.geometry} material={materials.LCD_Emissive} position={[0.324, 0.82, 0.665]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_348.geometry} material={materials.LCD_Emissive} position={[0.32, 0.819, 0.665]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_350.geometry} material={materials.LCD_Emissive} position={[0.315, 0.818, 0.664]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_352.geometry} material={materials.LCD_Emissive} position={[0.311, 0.816, 0.664]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_354.geometry} material={materials.LCD_Emissive} position={[0.307, 0.814, 0.663]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_356.geometry} material={materials.LCD_Emissive} position={[0.303, 0.812, 0.663]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_358.geometry} material={materials.LCD_Emissive} position={[0.3, 0.809, 0.662]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_360.geometry} material={materials.LCD_Emissive} position={[0.297, 0.807, 0.661]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_362.geometry} material={materials.LCD_Emissive} position={[0.293, 0.804, 0.66]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_364.geometry} material={materials.LCD_Emissive} position={[0.291, 0.8, 0.659]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_366.geometry} material={materials.LCD_Emissive} position={[0.288, 0.797, 0.658]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_368.geometry} material={materials.LCD_Emissive} position={[0.286, 0.793, 0.657]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_370.geometry} material={materials.LCD_Emissive} position={[0.284, 0.789, 0.656]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_372.geometry} material={materials.LCD_Emissive} position={[0.282, 0.785, 0.655]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_374.geometry} material={materials.LCD_Emissive} position={[0.281, 0.781, 0.654]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_376.geometry} material={materials.LCD_Emissive} position={[0.28, 0.777, 0.653]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_378.geometry} material={materials.LCD_Emissive} position={[0.28, 0.772, 0.651]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_380.geometry} material={materials.LCD_Emissive} position={[0.388, 0.785, 0.655]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_382.geometry} material={materials.material} position={[0.312, 0.734, 0.617]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_384.geometry} material={materials['Body_Paint_-_GT_Silver_Metalic']} position={[0, 0.47, 0.008]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_386.geometry} material={materials['Body_Paint_-_GT_Silver_Metalic']} position={[0.785, 0.537, 0.126]} rotation={[1.532, 0.087, 0.003]} />
          <mesh geometry={nodes.Object_388.geometry} material={materials['Body_Paint_-_GT_Silver_Metalic']} position={[-0.785, 0.537, 0.126]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_390.geometry} material={materials['Body_Paint_-_GT_Silver_Metalic']} position={[0.836, 0.514, 0.251]} />
          <mesh geometry={nodes.Object_392.geometry} material={materials['Body_Paint_-_GT_Silver_Metalic']} position={[-0.836, 0.514, 0.251]} />
          <mesh geometry={nodes.Object_394.geometry} material={materials.Carbon_Fiber_Yellow} position={[0, 0.785, -1.195]} />
          <mesh geometry={nodes.Object_396.geometry} material={materials['Metal_-_Chrome']} position={[0, 0.82, -0.483]} />
          <mesh geometry={nodes.Object_398.geometry} material={materials.Carbon_Fiber} position={[-0.001, 0.827, 0.088]} />
          <mesh geometry={nodes.Object_400.geometry} material={materials['Body_Paint_-_GT_Silver_Metalic']} position={[-0.038, 0.388, 2.053]} />
          <mesh geometry={nodes.Object_402.geometry} material={materials.Detail} position={[0, 0.216, 2.212]} />
          <mesh geometry={nodes.Object_404.geometry} material={materials['Plastic_-_Matte_Black']} position={[0, 0.342, 1.868]} />
          <mesh geometry={nodes.Object_406.geometry} material={materials['Plastic_-_Matte_Black']} position={[0, 0.364, 1.972]} />
          <mesh geometry={nodes.Object_408.geometry} material={materials.Carbon_Fiber} position={[0, 0.18, 2.105]} />
          <mesh geometry={nodes.Object_410.geometry} material={materials.Display} position={[0.335, 0.751, 0.626]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_412.geometry} material={materials.Window_Glass} position={[0.336, 0.759, 0.596]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_414.geometry} material={materials['Metal_-_Chrome']} position={[-0.649, 0.698, 0.119]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_416.geometry} material={materials.Window_Glass} position={[0.618, 0.952, -0.068]} />
          <mesh geometry={nodes.Object_418.geometry} material={materials.Window_Glass} position={[-0.618, 0.952, -0.068]} />
          <mesh geometry={nodes.Object_420.geometry} material={materials['Metal_-_Black']} position={[0.595, 0.379, 2.027]} rotation={[1.366, -0.357, -0.532]} />
          <mesh geometry={nodes.Object_422.geometry} material={materials['Metal_-_Black']} position={[0.599, 0.338, 2.018]} rotation={[1.364, -0.357, -0.536]} />
          <mesh geometry={nodes.Object_424.geometry} material={materials['Metal_-_Black']} position={[0.604, 0.293, 2.008]} rotation={[1.365, -0.357, -0.534]} />
          <mesh geometry={nodes.Object_426.geometry} material={materials['Metal_-_Black']} position={[0.609, 0.248, 1.998]} rotation={[1.364, -0.358, -0.535]} />
          <mesh geometry={nodes.Object_428.geometry} material={materials['Metal_-_Black']} position={[-0.595, 0.379, 2.027]} rotation={[1.366, 0.357, 0.532]} />
          <mesh geometry={nodes.Object_430.geometry} material={materials['Metal_-_Black']} position={[-0.604, 0.293, 2.008]} rotation={[1.365, 0.357, 0.534]} />
          <mesh geometry={nodes.Object_432.geometry} material={materials['Metal_-_Black']} position={[-0.599, 0.338, 2.018]} rotation={[1.364, 0.357, 0.536]} />
          <mesh geometry={nodes.Object_434.geometry} material={materials['Metal_-_Black']} position={[-0.609, 0.248, 1.998]} rotation={[1.364, 0.358, 0.535]} />
          <mesh geometry={nodes.Object_436.geometry} material={materials['Plastic_-_Glossy_BlackLights']} position={[0, 0.568, 1.874]} />
          <mesh geometry={nodes.Object_438.geometry} material={materials.Window_Glass} position={[0, 0.616, 1.86]} />
          <mesh geometry={nodes.Object_440.geometry} material={materials.Window_Glass} position={[0, 0.623, 1.747]} />
          <mesh geometry={nodes.Object_442.geometry} material={materials.Window_Glass} position={[0, 0.577, 1.646]} />
          <mesh geometry={nodes.Object_444.geometry} material={materials.Glass_Bumped_2} position={[0, 0.576, 1.663]} />
          <mesh geometry={nodes.Object_446.geometry} material={materials['Plastic_-_Glossy_BlackLights']} position={[0.005, 0.621, 1.733]} />
          <mesh geometry={nodes.Object_448.geometry} material={materials.Glass_Bumped} position={[0, 0.623, 1.753]} />
          <mesh geometry={nodes.Object_450.geometry} material={materials.Detail} position={[0.012, 0.623, 1.724]} />
          <mesh geometry={nodes.Object_452.geometry} material={materials['Metal_-_Chrome']} position={[0, 0.623, 1.724]} />
          <mesh geometry={nodes.Object_454.geometry} material={materials.Glass_Bumped_2} position={[0, 0.628, 1.735]} />
          <mesh geometry={nodes.Object_456.geometry} material={materials.Window_Glass} position={[0, 0.624, 1.755]} />
          <mesh geometry={nodes.Object_458.geometry} material={materials['Metal_-_Chrome']} position={[-0.654, 0.699, 0.189]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_460.geometry} material={materials['Plastic_-_Matte_Black']} position={[-0.68, 0.607, 0.394]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_462.geometry} material={materials['Interior_Detail_-_Palstic']} position={[-0.696, 0.488, 0.217]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_464.geometry} material={materials['Metal_-_Black']} position={[-0.67, 0.623, 0.333]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_466.geometry} material={materials['Plastic_-_Glossy_Black']} position={[-0.705, 0.524, 0.461]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_468.geometry} material={materials.Leather} position={[-0.635, 0.687, 0.341]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_470.geometry} material={materials['Interior_Detail_-_Matte']} position={[-0.752, 0.565, 0.492]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_472.geometry} material={materials.Rubber} position={[-0.701, 0.685, 0.175]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_474.geometry} material={materials.Leather} position={[0.655, 0.701, 0.293]} rotation={[1.532, 0.087, 0.003]} />
          <mesh geometry={nodes.Object_476.geometry} material={materials['Metal_-_Chrome']} position={[0.654, 0.699, 0.189]} rotation={[1.532, 0.087, 0.003]} />
          <mesh geometry={nodes.Object_478.geometry} material={materials.Rubber} position={[0.701, 0.685, 0.175]} rotation={[1.532, 0.087, 0.003]} />
          <mesh geometry={nodes.Object_480.geometry} material={materials['Plastic_-_Matte_Black']} position={[0.68, 0.607, 0.394]} rotation={[1.532, 0.087, 0.003]} />
          <mesh geometry={nodes.Object_482.geometry} material={materials.Leather} position={[0.635, 0.687, 0.341]} rotation={[1.532, 0.087, 0.003]} />
          <mesh geometry={nodes.Object_484.geometry} material={materials['Metal_-_Black']} position={[0.669, 0.628, 0.332]} rotation={[1.532, 0.087, 0.003]} />
          <mesh geometry={nodes.Object_486.geometry} material={materials['Interior_Detail_-_No_Transparent']} position={[0.689, 0.482, 0.284]} rotation={[1.532, 0.087, 0.003]} />
          <mesh geometry={nodes.Object_488.geometry} material={materials['Plastic_-_Glossy_Black']} position={[0.705, 0.524, 0.461]} rotation={[1.532, 0.087, 0.003]} />
          <mesh geometry={nodes.Object_490.geometry} material={materials['Interior_Detail_-_No_Transparent']} position={[0.752, 0.565, 0.492]} rotation={[1.532, 0.087, 0.003]} />
          <mesh geometry={nodes.Object_492.geometry} material={materials['Interior_Detail_-_Palstic']} position={[0.14, 0.669, 0.529]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_494.geometry} material={materials['Metal_-_Black']} position={[0.797, 0.714, -0.472]} />
          <mesh geometry={nodes.Object_496.geometry} material={materials.Detail} position={[0.823, 0.674, -0.473]} />
          <mesh geometry={nodes.Object_498.geometry} material={materials['Carbon_Fiber_-_Interior']} position={[0.68, 0.543, 0.114]} rotation={[1.532, 0.087, 0.003]} />
          <mesh geometry={nodes.Object_500.geometry} material={materials.Grid} position={[0, 0.905, -1.267]} />
          <mesh geometry={nodes.Object_502.geometry} material={materials['Metal_-_Black']} position={[0, 0.843, -1.182]} />
          <mesh geometry={nodes.Object_504.geometry} material={materials.Interior_Detail} position={[0.079, 0.653, 0.571]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_506.geometry} material={materials.Mirror} position={[0.931, 0.82, 0.467]} />
          <mesh geometry={nodes.Object_508.geometry} material={materials.Mirror} position={[0.013, 1.037, 0.405]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_510.geometry} material={materials.Carbon_Fiber} position={[0.904, 0.813, 0.495]} />
          <mesh geometry={nodes.Object_512.geometry} material={materials.Mirror} position={[-0.931, 0.82, 0.467]} />
          <mesh geometry={nodes.Object_514.geometry} material={materials.Carbon_Fiber} position={[-0.904, 0.813, 0.495]} />
          <mesh geometry={nodes.Object_516.geometry} material={materials.Window_Glass_not_transparent} position={[0, 0.982, 0.406]} />
          <mesh geometry={nodes.Object_518.geometry} material={materials['Plastic_-_Matte_Black']} position={[0, 0.541, -2.269]} rotation={[-0.209, 0, 0]} scale={[1.518, 1.085, 1]} />
          <mesh geometry={nodes.Object_520.geometry} material={materials['Body_Paint_-_GT_Silver_Metalic']} position={[-0.001, 0.55, -2.095]} />
          <mesh geometry={nodes.Object_522.geometry} material={materials['Plastic_-_Matte_Black']} position={[0, 0.526, -1.899]} />
          <mesh geometry={nodes.Object_524.geometry} material={materials.Carbon_Fiber} position={[0, 0.304, -2.077]} />
          <mesh geometry={nodes.Object_526.geometry} material={materials['Metal_-_Black']} position={[-0.797, 0.714, -0.472]} />
          <mesh geometry={nodes.Object_528.geometry} material={materials.Leather} position={[-0.655, 0.701, 0.293]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_530.geometry} material={materials.Detail} position={[-0.823, 0.674, -0.473]} />
          <mesh geometry={nodes.Object_532.geometry} material={materials['Carbon_Fiber_-_Interior']} position={[-0.68, 0.543, 0.114]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_534.geometry} material={materials['Interior_Detail_-_No_Transparent']} position={[0.335, 0.291, -0.114]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_536.geometry} material={materials['Interior_Detail_-_No_Transparent']} position={[0.339, 0.461, 0.048]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_538.geometry} material={materials.Interior_Detail} position={[-0.335, 0.291, -0.114]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_540.geometry} material={materials.INT_Seat_Logo} position={[0, 0.901, -0.301]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_542.geometry} material={materials.Fabric} position={[0, 0.506, -0.086]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_544.geometry} material={materials.Leather} position={[0, 0.932, -0.385]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_546.geometry} material={materials['Body_Paint_-_GT_Silver_Metalic']} position={[0.001, 0.803, -2.027]} />
          <mesh geometry={nodes.Object_548.geometry} material={materials.Carbon_Fiber} position={[0, 0.77, -2.031]} />
          <mesh geometry={nodes.Object_550.geometry} material={materials['Metal_-_Black']} position={[0, 0.717, -1.968]} />
          <mesh geometry={nodes.Object_552.geometry} material={materials['Metal_-_Black']} position={[0, 0.81, -2.03]} />
          <mesh geometry={nodes.Object_554.geometry} material={materials.Detail} position={[0, 0.806, -2.03]} />
          <mesh geometry={nodes.Object_556.geometry} material={materials['Metal_-_Black']} position={[-0.002, 0.801, -2.086]} />
          <mesh geometry={nodes.Object_558.geometry} material={materials['Plastic_-_Glossy_Black']} position={[0, 0.753, -2.091]} />
          <mesh geometry={nodes.Object_560.geometry} material={materials.Steering_wheel_Trim} position={[0.334, 0.897, 0.425]} rotation={[1.841, 0, 0]} />
          <mesh geometry={nodes.Object_562.geometry} material={materials['Leather_-_Dark']} position={[0.335, 0.743, 0.383]} rotation={[1.841, 0, 0]} />
          <mesh geometry={nodes.Object_564.geometry} material={materials['Plastic_-_Glossy_Black']} position={[0.314, 0.707, 0.392]} rotation={[1.841, 0, 0]} />
          <mesh geometry={nodes.Object_566.geometry} material={materials.Interior_Detail} position={[0.329, 0.705, 0.376]} rotation={[1.841, 0, 0]} />
          <mesh geometry={nodes.Object_568.geometry} material={materials['Interior_Detail_-_Matte']} position={[0.36, 0.682, 0.376]} rotation={[1.841, 0, 0]} />
          <mesh geometry={nodes.Object_570.geometry} material={materials['Metal_-_Chrome']} position={[0.343, 0.703, 0.387]} rotation={[1.841, 0, 0]} />
          <mesh geometry={nodes.Object_572.geometry} material={materials['Metal_-_Black']} position={[0.322, 0.692, 0.383]} rotation={[1.841, 0, 0]} />
          <mesh geometry={nodes.Object_574.geometry} material={materials['Carbon_Fiber_-_Interior']} position={[0.225, 0.729, 0.432]} rotation={[1.838, -0.22, -0.194]} />
          <mesh geometry={nodes.Object_576.geometry} material={materials['Carbon_Fiber_-_Interior']} position={[0.445, 0.729, 0.432]} rotation={[1.882, 0.183, 0.182]} />
          <mesh geometry={nodes.Object_578.geometry} material={materials.Stich} position={[0.634, 0.687, 0.342]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_580.geometry} material={materials.Stich} position={[-0.634, 0.687, 0.342]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_582.geometry} material={materials['Stich_-_All']} position={[0.334, 0.748, 0.386]} rotation={[1.841, 0, 0]} />
          <mesh geometry={nodes.Object_594.geometry} material={materials.Structure} position={[0.001, 0.685, -1.026]} />
          <mesh geometry={nodes.Object_596.geometry} material={materials['Interior_Detail_-_Palstic']} position={[0.573, 0.638, 0.519]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_598.geometry} material={materials['Interior_Detail_-_Palstic']} position={[0.573, 0.639, 0.514]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_600.geometry} material={materials.material} position={[0.209, 0.746, 0.613]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_602.geometry} material={materials.material_0} position={[0.312, 0.771, 0.644]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_604.geometry} material={materials.Glass_Bumped} position={[0, 0.336, -2.293]} />
          <mesh geometry={nodes.Object_606.geometry} material={materials['Metal_-_Chrome']} position={[0, 0.54, -2.157]} />
          <mesh geometry={nodes.Object_608.geometry} material={materials.Glass_Bumped} position={[0, 0.804, -2.157]} />
          <mesh geometry={nodes.Object_610.geometry} material={materials['Metal_-_Chrome']} position={[0, 0.805, -2.149]} rotation={[1.52, 0, 0]} />
          <mesh geometry={nodes.Object_612.geometry} material={materials.Detail} position={[0, 0.809, -2.134]} />
          <mesh geometry={nodes.Object_614.geometry} material={materials['Metal_-_Chrome']} position={[0, 0.809, -2.131]} rotation={[1.52, 0, 0]} />
          <mesh geometry={nodes.Object_616.geometry} material={materials.Detail} position={[0, 0.334, -2.277]} />
          <mesh geometry={nodes.Object_618.geometry} material={materials.Window_Glass_Red} position={[0, 0.727, -2.02]} />
          <mesh geometry={nodes.Object_620.geometry} material={materials.Tail_Light_Base} position={[0, 0.726, -1.997]} />
          <mesh geometry={nodes.Object_622.geometry} material={materials.Tail_Light_Base} position={[0, 0.731, -2.02]} />
          <mesh geometry={nodes.Object_624.geometry} material={materials.Glass_Bumped_2} position={[0, 0.736, -1.994]} />
          <mesh geometry={nodes.Object_626.geometry} material={materials.Window_Glass} position={[0, 0.982, 0.466]} />
          <mesh geometry={nodes.Object_628.geometry} material={materials['Metal_-_Black']} position={[-0.448, 0.811, 0.9]} />
          <mesh geometry={nodes.Object_630.geometry} material={materials['Metal_-_Black']} position={[-0.202, 0.79, 1.087]} />
        </group>
      </group>
      <group position={[0.857, 0.349, 1.656]} rotation={[1.622, 0, 0]}>
        <group position={[-0.857, 1.277, -0.348]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_633.geometry} material={materials.Tyre__Dirt_Version} />
          <mesh geometry={nodes.Object_635.geometry} material={materials.Detail} position={[0.916, 0.348, 1.129]} />
          <mesh geometry={nodes.Object_637.geometry} material={materials.Caliper} position={[0.884, 0.342, 1.119]} />
          <mesh geometry={nodes.Object_639.geometry} material={materials.Detail} position={[0.965, 0.348, 1.277]} />
          <mesh geometry={nodes.Object_641.geometry} material={materials.Rim_Screw} position={[0.955, 0.348, 1.277]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_643.geometry} material={materials.material_42} position={[0.942, 0.344, 1.277]} rotation={[Math.PI / 2, 0, 0]} />
        </group>
      </group>
      <group position={[-0.857, 0.349, 1.656]} rotation={[1.622, 0, 0]}>
        <group position={[0.857, 1.277, -0.348]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_646.geometry} material={materials.Tyre__Dirt_Version} />
          <mesh geometry={nodes.Object_648.geometry} material={materials.Detail} position={[-0.916, 0.348, 1.129]} />
          <mesh geometry={nodes.Object_650.geometry} material={materials.Caliper} position={[-0.888, 0.356, 1.119]} />
          <mesh geometry={nodes.Object_652.geometry} material={materials.Detail} position={[-0.965, 0.348, 1.277]} />
          <mesh geometry={nodes.Object_654.geometry} material={materials.Rim_Screw} position={[-0.955, 0.348, 1.277]} rotation={[Math.PI / 2, 0, Math.PI]} />
          <mesh geometry={nodes.Object_656.geometry} material={materials.material_42} position={[-0.942, 0.344, 1.277]} rotation={[Math.PI / 2, 0, Math.PI]} />
        </group>
      </group>
      <group position={[0.832, 0.367, -1.076]} rotation={[1.782, 0, 0]}>
        <group position={[-0.832, -1.455, -0.367]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_659.geometry} material={materials.Tyre__Dirt_Version} />
          <mesh geometry={nodes.Object_661.geometry} material={materials.Detail} position={[0.883, 0.356, -1.305]} />
          <mesh geometry={nodes.Object_663.geometry} material={materials.Caliper} position={[0.849, 0.347, -1.292]} />
          <mesh geometry={nodes.Object_665.geometry} material={materials.Detail} position={[0.942, 0.367, -1.455]} />
          <mesh geometry={nodes.Object_667.geometry} material={materials.Rim_Screw} position={[0.932, 0.367, -1.455]} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_669.geometry} material={materials.material_42} position={[0.935, 0.363, -1.455]} rotation={[Math.PI / 2, 0, 0]} />
        </group>
      </group>
      <group position={[-0.831, 0.367, -1.076]} rotation={[1.782, 0, 0]}>
        <group position={[0.831, -1.455, -0.367]} rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_672.geometry} material={materials.Tyre__Dirt_Version} />
          <mesh geometry={nodes.Object_674.geometry} material={materials.Caliper} position={[-0.849, 0.362, -1.291]} />
          <mesh geometry={nodes.Object_676.geometry} material={materials.Detail} position={[-0.883, 0.356, -1.305]} />
          <mesh geometry={nodes.Object_678.geometry} material={materials.Detail} position={[-0.942, 0.367, -1.455]} />
          <mesh geometry={nodes.Object_680.geometry} material={materials.Rim_Screw} position={[-0.93, 0.367, -1.455]} rotation={[Math.PI / 2, 0, Math.PI]} />
          <mesh geometry={nodes.Object_682.geometry} material={materials.material_42} position={[-0.934, 0.363, -1.455]} rotation={[Math.PI / 2, 0, Math.PI]} />
        </group>
      </group>
      <group position={[0.852, 0.349, 1.656]} rotation={[-1.571, 0, 0]}>
        <mesh geometry={nodes.Object_685.geometry} material={materials.Disc} position={[-0.852, 1.277, -0.348]} rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-0.852, 0.349, 1.656]} rotation={[-1.571, 0, 0]}>
        <mesh geometry={nodes.Object_688.geometry} material={materials.Disc} position={[0.852, 1.277, -0.348]} rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[0.819, 0.367, -1.076]} rotation={[-1.571, 0, 0]}>
        <mesh geometry={nodes.Object_691.geometry} material={materials.Disc} position={[-0.819, -1.455, -0.367]} rotation={[Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-0.817, 0.367, -1.076]} rotation={[-1.571, 0, 0]}>
        <mesh geometry={nodes.Object_694.geometry} material={materials.Disc} position={[0.817, -1.455, -0.367]} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/2014_-_porsche_918_spyder_rigged__mid-poly.glb')
